sudo: false
language: node_js
node_js:
  - node
services:
  - mongodb

cache: yarn

before_install:
  - npm install -g grunt
  - npm install -g grunt-cli

script:
  - npm run build
  - npm test

after_success:
  - npm run codacy